version: '3.8'           

services:
  frontend:
    image: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: bloglist-frontend-dev
  backend:
    image: bloglist-backend-dev
    build: 
      context: ./bloglist-backend/
      dockerfile: dev.Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./bloglist-backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: bloglist-backend-dev
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb+srv://fsadmin:fullstackopen@cluster0.9gimx.mongodb.net/blog-app?retryWrites=true&w=majority
      - TEST_MONGODB_URI=mongodb+srv://fsadmin:fullstackopen@cluster0.9gimx.mongodb.net/blog-app-test?retryWrites=true
      - SECRET=halojaa
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: